---
version: "3"
services:
 devopsdb:
   image: kaveridevops/myapp:appimage
   ports:
     - "4444:8086"
   depends_on:
     - "devopsdb"  
   deploy:
     replicas: 2

 application:
   image: kaveridevops/mydb:dbimage
   ports:
     - "9999:3306"
   deploy:
      replicas: 2  
