---
version: "3"
services:
 devopsdb:
   image: kaveridevops/mynewapp:dbimage
   ports:
     - "4444:3306"

 application:
   image: kaveridevops/mynewapp:appimage
   ports:
     - "9999:8080"
   depends_on:
     - "devopsdb"
